name: deploy nodejs 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Upload the node modules for next jobs
      uses: actions/upload-artifact@v3
      with:
          name: node_modules
          path: ./node_modules
          
  deploy: 
     runs-on: ubuntu-latest
     needs: build
    
  steps: 
    - name: checkout code
      uses: actions/checkout@v3
    - name: Downoad the artifact from the build job that we uploaded
      uses: actions/download-artifact@v3
      with:
          name: node_modules
          path: ./node_modules
    - name: Set up ssh key
      run: |
          echo "${{secrets.PRIVATE_KEY}}" >> suren.pem
          chmod 600 suren.pem
          
  
    - name: copy files to ec2
      run: |
        scp -i suren.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r ./* ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu
       
   
    - name: Install Mysql
      run: |
         ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP }} 'sudo apt-get update -y && sudo apt-get install mysql-server -y'
    
    - name: Start MySQL service
      run: |
          ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP }} 'sudo systemctl start mysql'
    
    
    
    - name: Create Mysql User
      run: |
        ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
        sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'suren'@'%' IDENTIFIED WITH mysql_native_password BY 'sush123';"
        sudo mysql -u root -e "GRANT USAGE ON *.* TO 'suren'@'%';"
        sudo mysql -u root -e "ALTER USER 'suren'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
        sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'suren1'@'%';"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
        exit
        EOF



    - name: Create database using the user we just created 
      run: |
        ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP }} << EOF
        sudo mysql -u suren -psuren123 -e "CREATE DATABASE IF NOT EXISTS my_db;"
        EOF

    - name: Create Table
      run: |
          ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP}} 'mysql -u suren -psuren123 -h localhost  -D my_db -e "CREATE TABLE IF NOT EXISTS employee (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), phone VARCHAR(255), email VARCHAR(255), address VARCHAR(255));"'
    - name: Install pm2
      run: |
       ssh -o StrictHostKeyChecking=no -i suren.pem ubuntu@${{ secrets.EC2_IP }} '
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash &&
        export NVM_DIR="$HOME/.nvm" &&
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" &&
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" &&
        nvm install --lts
        cd /home/ubuntu &&
        npm install
        npm i mysql2
        node app.js
        '
        

    
